#' A edgeRAnaGO Function
#'
#' This function did go analysis
#' @param lrts a list of lrt fit object which generated by edgeRdfGenes
#' @param fdr false discovery rate cutoff for differentially expressed genes. Numeric value between 0 and 1
#' @param dir directory which count files are located
#' @param comparisons pairwise comparisons
#' @param outprefix the prefix of output file
#' @keywords pathway analysis
#' @export
#' @examples edgeRAnaGO(pathway, up=FALSE)
#' edgeRAnaGO()

edgeRAnaGO <- function(lrts, fdr=0.05, dir, comparisons, outprefix,spe){
  #GO analysis
  all = data.frame(GOID=character(), Term=character(),Ont=character(), N=integer(),
                   Up=integer(), Down=integer(),
                   P.Up=double(), P.Down=double(),
                   FDR_up=double(), FDR_down=double(),
                   Comparison=character())

  if (spe == "human"){
    go_species = "Hs"
  }
  else if (spe=="rat"){
    go_species = "Rn"
  }
  
  for (i in (1:length(lrts))){
    lrt = lrts[[i]]
    c = comparisons[[i]]
    go <- goana(lrt, FDR=fdr, species=go_species)
    go_results <- topGO(go, number=Inf)
    go_results$FDR_up = p.adjust(go_results$P.Up, method="BH")
    go_results$FDR_down = p.adjust(go_results$P.Down, method="BH")
    go_results$Comparison = rep(c, dim(go_results)[1])
    
    GOID <- rownames(go_results)
    go_results <- cbind(GOID, go_results)
    
    
    all <- rbind(all, go_results)
    go_file <- paste(c, "_go.txt", sep = "")
    write.table(go_results, file.path(dir,go_file), sep="\t", quote = F, row.names = F)
  }
  all_out = file.path(dir,paste(outprefix, "_go_all.txt", sep=""))
  write.table(go_results, all_out,sep="\t", quote=F)
  return(all)
}





