#' A edgeRAnaKEGG Function
#'
#' This function did KEGG pathway analysis based on edgeR
#' @param lrts a list of lrt fit object which generated by edgeRdfGenes
#' @param dfCutOff false discovery rate cutoff for differentially expressed genes. Numeric value between 0 and 1
#' @param dir directory which count files are located
#' @param comparisons pairwise comparisons
#' @param outprefix the prefix of output file
#' @keywords pathway analysis
#' @export
#' @examples edgeRAnaKEGG(pathway, up=FALSE)
#' edgeRAnaKEGG()

edgeRAnaKEGG <- function(lrts, dfCutOff=0.05, dir, comparisons, outprefix, spe){
  #kegg pathway analysis
  all = data.frame(PathID=integer(), Pathway=character(), N=integer(),
                  Up=integer(), Down=integer(),
                  P.Up=double(), P.Down=double(),
                  FDR_up=double(), FDR_down=double(),
                  Comparison=character())
  if (spe=="human"){
    kegg_species = "Hs"
  }
  else if (spe=="rat"){
    kegg_species = "Rn"
  }
  for (i in (1:length(lrts))){
    lrt = lrts[[i]]
    c = comparisons[[i]]
    keg <- kegga(lrt, FDR=dfCutOff, species=kegg_species)
    kegg_results <- topKEGG(keg, number=Inf)
    kegg_results$FDR_up = p.adjust(kegg_results$P.Up, method="BH")
    kegg_results$FDR_down = p.adjust(kegg_results$P.Down, method="BH")
    kegg_results$Comparison = rep(c, dim(kegg_results)[1])
    
    #kegg_results$FDR_up = format(kegg_results$FDR_up, scientific=T)
    #kegg_results$FDR_down = format(kegg_results$FDR_down, scientific = T)
    #kegg_results$P.Up = format(kegg_results$P.Up, scientific=T)
    #kegg_results$P.Down = format(kegg_results$P.Down, scientific = T)
 
    PathID <- rownames(kegg_results)
    kegg_results <- cbind(PathID, kegg_results)
    all <- rbind(all, kegg_results)
    print(dim(all))
    kegg_file <- paste(c, "_kegg.txt", sep = "")
    write.table(kegg_results, file.path(dir,kegg_file), sep="\t",quote = F, row.names = F)
  }
  all_out = file.path(dir, paste(outprefix, "_kegg_all.txt", sep=""))
  write.table(all, all_out, sep="\t", quote=F, row.names=F)
  return(all)
}





