#' A edgeRAnaMapedGene2Pathway Function
#'
#' This function generate the fit model based on edgeR
#' @param pathways a list of lrt fit object which generated by edgeRdfGenes
#' @param df false discovery rate cutoff for differentially expressed genes. Numeric value between 0 and 1
#' @keywords pathway analysis
#' @export
#' @examples edgeRAnaMapedGene2Pathway(pathways, df)
#' edgeRAnaMapedGene2Pathway()

edgeRAnaMapedGene2Pathway <- function(sign_path, df, dfCutoff, out=T, dir=NA, outprefix=NA, spe){
  df = df[df$FDR<dfCutoff,]
  df$GeneID = rownames(df)
  
  #get all kegg gene and pathway information
  if (spe =="human"){
    info <-getGeneKEGGLinks(species.KEGG = "hsa", convert = FALSE)
  }
  else if (spe=="rat"){
    info <-getGeneKEGGLinks(species.KEGG = "rno", convert = FALSE)
  }
  pathways = sign_path
  pathways = merge(pathways, info, by.x="PathID", by.y = "PathwayID", all = F)
  pathways = pathways[,c(1, 10, dim(pathways)[2])]
  
  library(dplyr)
  path_genes = pathways %>% inner_join(df, by=c("GeneID"="EntrezID", "Comparison" = "Comparison"))
                                       # merge(df, pathways, by=c("GeneID", "Comparison"), all.y= T )

  path_genes <- path_genes[,c(1,3,5,9,4,2)]
  colnames(path_genes) <- c('PathID','GeneID', 'logFC','FDR', 'Gene', 'Comparison')

  if (out==T){
    out_file <- paste(outprefix, "_mapped_gene_to_pathway.txt", sep="")
    write.table(path_genes, file.path(dir,out_file),sep="\t", quote=F, row.names = F)
  }

  return(path_genes)

  }
